<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    const SUCCESS = 'success';
    const ERROR = 'error';

    const ERR_INVALID_UNKNOWN = 'ERR_INVALID_UNKNOWN';
    const ERR_INVALID_USER_EMAIL = 'ERR_INVALID_USER_EMAIL';
    const ERR_INVALID_PASSWORD  = 'ERR_INVALID_PASSWORD';
    const ERR_INVALID_LOCATION  = 'ERR_INVALID_LOCATION';
    const ERR_INVALID_SHIFT_ID  = 'ERR_INVALID_SHIFT_ID';
    const ERR_INVALID_FIELD_ID  = 'ERR_INVALID_FIELD_ID';
    const ERR_INVALID_STAFF_STATUS_ID  = 'ERR_INVALID_STAFF_STATUS_ID';
    const ERR_INVALID_CHECKED  = 'ERR_INVALID_CHECKED';
    const ERR_INVALID_HEALTH_STATUS  = 'ERR_INVALID_HEALTH_STATUS';
    const ERR_INVALID_S_DATE  = 'ERR_INVALID_S_DATE';
    const ERR_INVALID_E_DATE  = 'ERR_INVALID_E_DATE';
    const ERR_INVALID_REST_DATE  = 'ERR_INVALID_REST_DATE';
    const ERR_INVALID_E_LEAVE_TIME  = 'ERR_INVALID_E_LEAVE_TIME';
    const ERR_INVALID_OVER_TIME  = 'ERR_INVALID_OVER_TIME';
    const ERR_INVALID_ALT_DATE  = 'ERR_INVALID_ALT_DATE';
    const ERR_INVALID_BREAK_TIME  = 'ERR_INVALID_BREAK_TIME';
    const ERR_INVALID_SHIFT_S_TIME  = 'ERR_INVALID_SHIFT_S_TIME';
    const ERR_INVALID_SHIFT_E_TIME  = 'ERR_INVALID_SHIFT_E_TIME';
    const ERR_INVALID_SHIFT_ALT_DATE  = 'ERR_INVALID_SHIFT_ALT_DATE';
    const ERR_INVALID_SHIFT_LIST  = 'ERR_INVALID_SHIFT_LIST';
    const ERR_INVALID_ARRIVE_CHECKED_AT  = 'ERR_INVALID_ARRIVE_CHECKED_AT';
    const ERR_INVALID_LEAVE_CHECKED_AT  = 'ERR_INVALID_LEAVE_CHECKED_AT';
    const ERR_INVALID_BREAK_S_TIME  = 'ERR_INVALID_BREAK_S_TIME';
    const ERR_INVALID_NIGHT_BREAK_S_TIME  = 'ERR_INVALID_NIGHT_BREAK_S_TIME';
    const ERR_INVALID_NIGHT_BREAK_TIME  = 'ERR_INVALID_NIGHT_BREAK_TIME';
    const ERR_INVALID_ARRIVE_TIME  = 'ERR_INVALID_ARRIVE_TIME';
    const ERR_INVALID_LEAVE_TIME  = 'ERR_INVALID_LEAVE_TIME';
}
